apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logging
  name: logging
spec:
  containers:
  - image: nginx
    name: logging
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
