apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: monitoring
  name: monitoring
spec:
  containers:
  - image: nginx
    name: monitoring
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
